# Generated by Django 3.1.7 on 2021-05-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userlecturelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lecture_list',
        ),
        migrations.AddField(
            model_name='user',
            name='lecture_list',
            field=models.ManyToManyField(related_name='users', through='register.UserLectureList', to='register.Lecture'),
        ),
    ]
