# Generated by Django 3.1.7 on 2021-05-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210523_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureeva',
            name='gakunen_lank',
            field=models.IntegerField(choices=[(1, '１年'), (2, '２年'), (3, '３年'), (4, '４年')], default=1, verbose_name='履修者の学年'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lectureeva',
            name='eva_lank',
            field=models.IntegerField(choices=[(5, '多い'), (4, 'やや多い'), (3, '普通'), (2, 'やや少ない'), (1, '少ない')], verbose_name='課題量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lecture_list',
            field=models.ManyToManyField(blank=True, through='register.UserLectureList', to='register.Lecture', verbose_name='履修講義名'),
        ),
    ]
