# Generated by Django 3.1 on 2021-05-28 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210525_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureeva',
            name='gakunen_lank',
            field=models.IntegerField(choices=[(1, '１年'), (2, '２年'), (3, '３年'), (4, '４年')], verbose_name='学年'),
        ),
        migrations.AlterField(
            model_name='user',
            name='college_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='register.college', verbose_name='大学名'),
        ),
    ]
