# Generated by Django 3.1 on 2021-06-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_lecturechat_chat_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_point',
            field=models.IntegerField(default=0, verbose_name='ユーザーポイント'),
        ),
        migrations.AlterField(
            model_name='lecturechat',
            name='chat_text',
            field=models.TextField(max_length=1000, verbose_name='投稿'),
        ),
    ]
