# Generated by Django 3.1 on 2021-06-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20210616_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureeva',
            name='place',
            field=models.IntegerField(choices=[(0, '対面'), (1, 'オンライン')], default=0, verbose_name='授業方式'),
            preserve_default=False,
        ),
    ]
