# Generated by Django 3.1 on 2021-06-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_lectureeva_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureeva',
            name='place',
            field=models.IntegerField(choices=[(1, '対面'), (2, 'オンライン')], verbose_name='授業方式'),
        ),
    ]
