# Generated by Django 3.1 on 2021-07-17 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20210714_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_product',
            name='buy_user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='buy_user', to='register.user', verbose_name='購入者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='text_product',
            name='sale_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_user', to=settings.AUTH_USER_MODEL, verbose_name='出品者'),
        ),
    ]
