# Generated by Django 3.1 on 2021-07-22 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_text_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_product',
            name='product_ID',
            field=models.CharField(default=1, max_length=200, verbose_name='商品コード'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text_product',
            name='sale_done',
            field=models.BooleanField(default=False, verbose_name='購買手続きが終了したかテェック'),
        ),
        migrations.AlterField(
            model_name='text_product',
            name='image',
            field=models.FileField(upload_to='product_image/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'HEIC'])], verbose_name='商品画像'),
        ),
    ]
