# Generated by Django 3.1 on 2021-08-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_auto_20210722_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_product',
            name='product_ID',
        ),
    ]
