# Generated by Django 3.1 on 2021-08-05 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_remove_text_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_text', models.TextField(max_length=1000, verbose_name='本文')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.text_product', verbose_name='教科書')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
