# Generated by Django 3.1 on 2021-08-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_text_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_product',
            name='trade_eva',
            field=models.BooleanField(default=True, verbose_name='取引の評価'),
        ),
    ]
