# Generated by Django 3.1 on 2021-10-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_text_product_trade_eva'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_product',
            name='pass_place',
            field=models.TextField(default='チャットにて相談', verbose_name='受け渡し日時/場所'),
        ),
    ]
