# Generated by Django 3.1 on 2021-11-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_text_product_pass_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_product',
            name='buy_user',
        ),
        migrations.RemoveField(
            model_name='text_product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='text_product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='text_product',
            name='sale_done',
        ),
        migrations.RemoveField(
            model_name='text_product',
            name='sale_user',
        ),
        migrations.RemoveField(
            model_name='text_product',
            name='trade_eva',
        ),
        migrations.AlterField(
            model_name='text_product',
            name='pass_place',
            field=models.TextField(default='', verbose_name='受け渡し日時/場所'),
        ),
        migrations.DeleteModel(
            name='Text_chat',
        ),
    ]
