# Generated by Django 3.1 on 2021-11-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_text_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_product',
            name='url',
            field=models.URLField(verbose_name='商品URL'),
        ),
    ]
