# Generated by Django 3.1 on 2021-12-25 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0033_board_status_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='user_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_list', to=settings.AUTH_USER_MODEL, verbose_name='所属ユーザー'),
        ),
    ]
