# Generated by Django 3.1 on 2022-01-03 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0035_auto_20211227_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='editor_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='editor_list', to=settings.AUTH_USER_MODEL, verbose_name='編集ユーザー'),
        ),
    ]
