# Generated by Django 3.1 on 2022-02-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0036_circle_editor_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='input_invi_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invi_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invi_point',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_point',
        ),
        migrations.AddField(
            model_name='lectureeva',
            name='everyweek_time',
            field=models.IntegerField(choices=[(1, '１年'), (2, '２年'), (3, '３年'), (4, '４年')], default=1, verbose_name='課題/テスト勉強時間(毎週)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectureeva',
            name='last_time',
            field=models.IntegerField(choices=[(1, '１年'), (2, '２年'), (3, '３年'), (4, '４年')], default=1, verbose_name='課題/テスト勉強時間(毎週)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(choices=[(1, '１年'), (2, '２年'), (3, '３年'), (4, '４年')], default=1, verbose_name='学年'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.FileField(blank=True, upload_to='board_images/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='lectureeva',
            name='dif_lank',
            field=models.IntegerField(choices=[(5, '簡単'), (4, 'やや簡単'), (3, '普通'), (2, 'やや難しい'), (1, '難しい')], verbose_name='難易度'),
        ),
        migrations.AlterField(
            model_name='lectureeva',
            name='eva_lank',
            field=models.IntegerField(choices=[(5, 'S'), (4, 'A'), (3, 'B'), (2, 'C'), (1, 'D')], verbose_name='総合評価'),
        ),
    ]
